services:
  dev:
    build:
      context: .
    # OR
    # image: 
    container_name: svelte-dev1
    # user: '1000:1000'
    ports:
      - 5173:5173
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
